### ISSUE TITLE
Migration to the new community APIs

### ISSUE THREAD

**Issue by Dawidores** [kevinclement/SimpleArmory#222]
Hello, I have such a problem because on the server defias brotherhood can not search my characters. The same goes for burning legion and silvermoon. Regio EU. 
Thanks in advance for your help!

**Comment by seirl** [comment]
Could you please be more specific? What are you doing, what did you expect would happen and what happens instead?

**Comment by Dawidores** [comment]
I have been interested in collecting mounts for some time. I was looking for good programs / addons that would help me collect the largest possible number of mounts, I found this page, and when choosing a server and entering the name of the character appears "Could not fetch 'Dawidor' from server 'defias-brotherhood'. Click here to try again. ". I would like to see what mounts I have to get, how to get them etc.

**Comment by BrandenWilliams** [comment]
I'm having the same problem. I cant look at any of my characters, my wifes, or even my best friends spread across several servers. 

Lostmuted - Spinebreaker is my main if you want an example. it comes back with
Error
Could not fetch 'Lostmuted' from server 'spinebreaker'. Click here to try again.

**Comment by zaphon** [comment]
I'll respond here even though I don't think it's related.  It appears that with Blizzard retiring the Community API yesterday (https://us.forums.blizzard.com/en/blizzard/t/wow-community-api-turned-off/4281) that SimpleArmory is now dead (there's a few other sites as well).  At least that is my guess as to why nothing is working (as I had to port my own app yesterday as well).  Good luck if this is what it is, the new API's are pretty terrible IMHO.

**Comment by seirl** [comment]
My understanding was that #167 migrated to the new community APIs, maybe some are missing?

**Comment by zaphon** [comment]
It's very possible than it's something completely unrelated.  Though honestly I tried porting my own apps months ago and couldn't do to most of the API being incomplete.  So not sure how they could have fully done it back in November of 2019.  Heck I'm still missing data that is "IN PROGRESS" as of today on the new API.

**Comment by gmsbaptista** [comment]
I am also getting the same error: "Could not fetch 'Khudan' from server 'chamber-of-aspects'. Click here to try again."

No other information

**Comment by zaphon** [comment]
I did review the checkin above, and what's happening is SA is hitting the old character API first, if that fails (it's getting a 404 now), it hits the new profile API which is returning a 500 error.  It uses it's own proxy to do this so I can't determine where the error is.

**Comment by zaphon** [comment]
And based on issues I ran into, looking at the proxy.js code I would bet that it's because he's not passing in a locale to the call.  The URL looks OK otherwise.  And yeah it shouldn't throw a 500 when you omit the locale, but it was for me as well.  So it may literally be as easy as appending a &locale=en_US to the end of the profile API URL.

**Comment by kevinclement** [comment]
The proxy is using: https://${region}.api.blizzard.com/wow/character/.

I'm not able to get their API to work on their api sample site.  It seems like it's an outage on their end.  When I read the docs on how to migrate, it points me to do all the changes I did.

**Comment by kevinclement** [comment]
Hmm, looks like I'm now able to get responses from their service.  I'll poke around

**Comment by zaphon** [comment]
Yeah I took your proxy.js code about 4 hours ago and isolated it to just the new profile code and it appears to work without throwing a 500 error.  Not sure you'll be able to parse the resultant JSON since it's different than what you get from the old api, but it was getting data back.

**Comment by kevinclement** [comment]
Ugh.  I think I have it sorted out, just going to take a little bit to fix it all up.  No clue why I thought previous change was sufficient.  For now I've deployed a small change that fixes the achievements, but now working on longer fix for all of it.  Need to deploy new proxy and then client change.  Gonna take me a couple hours

**Comment by BrandenWilliams** [comment]
freakin blizzard. i was thinking about messing around with an addon idea but after reading this thread it sounds like its a bad time lol

**Comment by seirl** [comment]
> No clue why I thought previous change was sufficient.

It's probably because they hadn't released the new APIs yet as @zaphon said, so the changes probably looked sufficient at the time.

**Comment by zaphon** [comment]
> freakin blizzard. i was thinking about messing around with an addon idea but after reading this thread it sounds like its a bad time lol

Good news is this is all backend API's used by websites / standalone apps vs an AddOn that's built in LUA and runs within the game client.  While there is change from release to release on the AddOn side of things, it's not as drastic as what occurred here.  I have a few addons that I wrote back in Vanilla that still work today with only minor changes over the past 15+ years.

As for the API change, it was a MASSIVE change, where they not only completely changed how it works, but it seems to have been written by someone who saw some cool article on a blog and said "we should do this" where they didn't take into consideration any real use cases.  What used to be 1 API call is now MANY API calls (mine went from 1 per user to 5 per user, and will get 2 more calls when they finish the API migration (yeah they turned off the old one before they even fully completed the new one)).  This has also resulted in me getting random errors / timeouts / etc. when hitting these new API's with much more volume than I used to (and I literally am only tracking my spouse and I's 150 characters or so, my apps aren't public at the moment).

**Comment by kevinclement** [comment]
Ya, it's was a pretty big takeaway from what they had.  Seems like folks working on it maybe didn't try to build an app with it.

I worked a little more on this last night.  The achievement stuff was straight forward, but the mounts are not.  The mount list you get back now has IDs that previously have not been seen.  So this is going to take some thinking about how to now map that to wowhead properly, unless wowhead magically does work to start using these new IDs.

**Comment by zaphon** [comment]
Welcome to the frustration of the new API.  Luckily wow.tools has built some tables that help with the translation since you can no longer translate the "new" mount ID to the old "spell ID" in order to link to things such as wowhead.  For example for the mounts you can use this https://wow.tools/dbc/?dbc=mount&build=8.3.0.33528  I have been calling this new API a dumpster fire for quite a while, and now we're stuck with it.

**Comment by seirl** [comment]
I thought you were joking and that the item ID would be available *somewhere* at least, maybe in the `/mount/{id}` endpoint, but no. What the hell.

**Comment by kevinclement** [comment]
oh, nice.  That tool might work for me then to update the local json files.  I was just going to do a brute force mapping the names to stitch them together.  This seems like it might be easier.

**Comment by kevinclement** [comment]
ok, did the first round of this using CSV from wow tools and I'm making progress.  I was able to update the local db with a script and that fixed almost all of them.  I think I'll push that change out just so I can incrementally be fixing stuff as it happens instead of waiting

**Comment by kevinclement** [comment]
shoot, now I have to do the same for pets, but doesn't seem like there is a quick mapping for that in the tools database.  I'll have to figure out how that gets materialized.

**Comment by zaphon** [comment]
https://wow.tools/dbc/?dbc=battlepetspecies&build=8.3.0.33724 doesn't have what you need?

**Comment by kevinclement** [comment]
Yup! I think that will work, wasn't sure if that was just battle pets and maybe didn't include companions, but I think it's a super set.  

I also found ItemToBattlePet that would have worked.  Gonna try with yours and see how far that gets me.

**Comment by zaphon** [comment]
Yeah I just started clicking on them all looking for a table.  I agree that's a ODDLY named file, but it seemed to have what was necessary.

**Comment by kevinclement** [comment]
sweet, I think that worked.  Just pushed change for pets.  Getting there :)

**Comment by kevinclement** [comment]
battlepets fixed and pushed.  No surprise, but some of the api data returned changed so had to tweak a bit.

**Comment by kevinclement** [comment]
oh, I also fixed the profile avatar image in header

**Comment by kevinclement** [comment]
phew, ok, reps finished, and also fixed up planner.  that should be everything.  all changes are pushed and live now.  closing out this bug.

**Comment by gmsbaptista** [comment]
Hey, sorry to bother, but I'm still getting the same error.
"Error
Could not fetch 'Khudan' from server 'chamber-of-aspects'. Click here to try again."
I tried different browsers and incognito mode, but always the same result...

**Comment by kevinclement** [comment]
Thanks for reaching out.   I'll take a look tonight, I think servers with dashes might bee causing issues.  My server is working fine and I saw another report with a dashed server, so that seems suspicious.

**Comment by grumple-higi** [comment]
> Thanks for reaching out. I'll take a look tonight, I think servers with dashes might bee causing issues. My server is working fine and I saw another report with a dashed server, so that seems suspicious.

Put your name in all lower case for now.  The API is picky and the site isn't lowering it.

**Comment by kevinclement** [comment]
Good catch.  I can reproduce this with my account too.  That should be a easy fix then, I'll work on it shortly.

**Comment by kevinclement** [comment]
ok, deployed fix that will lowercase it before it calls blizzard api, should be fixed.  I tested with Khudan and it's working now.

**Comment by Kolnevar** [comment]
Still getting an error when trying to access a character on Zul'jin.  Message reads "Could not fetch 'kolnevar' from server 'zuljin'. Click here to try again." Maybe a missing apostrophe?

**Comment by Raistliiin** [comment]
Not sure you are still working on this:

Could not fetch 'raistliin' from server 'scarlet-crusade'.  Click here to try again.  I have tried it with other machines and browsers, characters all the same results.  has been this way since 8.3
